# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"product_moment_corr": "encoding.ipynb",
         "get_model_plus_scores": "encoding.ipynb",
         "BlockMultiOutput": "encoding.ipynb",
         "preprocess_bold_fmri": "preprocessing.ipynb",
         "get_remove_idx": "preprocessing.ipynb",
         "generate_lagged_stimulus": "preprocessing.ipynb",
         "make_X_Y": "preprocessing.ipynb",
         "create_stim_filename_from_args": "process_bids.ipynb",
         "create_output_filename_from_args": "process_bids.ipynb",
         "create_metadata_filename_from_args": "process_bids.ipynb",
         "create_bold_glob_from_args": "process_bids.ipynb",
         "run": "process_bids.ipynb",
         "get_func_bold_directory": "process_bids.ipynb",
         "process_bids_subject": "process_bids.ipynb",
         "run_model_for_subject": "process_bids.ipynb"}

modules = ["encoding.py",
           "preprocessing.py",
           "process_bids.py"]

doc_url = "https://mjboos.github.io/voxelwiseencoding/"

git_url = "https://github.com/mjboos/voxelwiseencoding/tree/master/"

def custom_doc_links(name): return None
